### ISSUE TITLE
Replace custom report with lsd-core report?

### ISSUE THREAD

**Issue by nickmcdowall** [lsd-consulting/lsd-distributed-generator-ui#9]
What are your thoughts on replacing the custom pebble template for the report with the lsd-core report? This would remove the need to maintain two models and templates. The custom report is also still on pebble which may be painful to migrate to mustache template engine.

PS the latest report is a little more flexible with regards to some of the sections - i.e. the contents section is now tucked away and the details section is also optional now. (Although the start time and end time could be put in there to preserve the information that is available now).

I'm more than happy so come up with an example of what it looks like if that sounds good to you?

**Comment by lukasz-gryzbon** [comment]
I'm all for it!

> I'm more than happy so come up with an example of what it looks like if that sounds good to you?

That would be very helpful! Thanks!

**Comment by nickmcdowall** [comment]
OK cool, with an initial switch to the lsd-core renderes we get something like this:

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/1330362/230995268-eff0dec4-68c9-463c-be78-d0eba2e2283b.png">

(We could have the date range in the scenario description instead but felt like the facts was a good fit so stuck it in there instead)

I would also need to resolve the `css` and `javascript` references on the lsd-core side first though - I have an open `Issue` for making it configurable (i.e. option to either point to the github url or local files).

**Comment by lukasz-gryzbon** [comment]
Btw, it looks better than it does at the moment 😄 

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/5703054/231249028-2c37dd11-1acf-4f8f-86ea-6c1b55638f34.png">

**Comment by lukasz-gryzbon** [comment]
Are you planning to raise a PR for this?

**Comment by nickmcdowall** [comment]
> That looks good.
> 
> Only one question - where would the arrow lead? Back one page? If so, that fine.

Hey, I was also thinking about that - I guess it is only useful when the user creates an index page (which is probably quite rare to be honest..). I'll remove it (and possibly think about an alternative if necessary)

**Comment by nickmcdowall** [comment]
> Are you planning to raise a PR for this?

That's the plan - but needs the lsd-core fixes first which is nearly done now.

**Comment by nickmcdowall** [comment]
(PR raised)
